data_root: "../Base_de_Datos_Habla_Imaginada"
processed_root: "C:\\Users\\SantaFe-Tech\\Desktop\\Enzo_Catorano\\Universidad\\Extracurricular_investigacion\\tesis_cientibeca\\data\\processed"
fs: 1024
